### ISSUE TITLE
Local MicrobiomeAnalystR

### ISSUE THREAD

**Issue by Aciole-David** [xia-lab/MicrobiomeAnalystR#1]
Hello!
Thanks for the great work on MicrobiomeAnalyst.
Is there a way to install MicrobiomeAnalystR in a local R environment?
I was looking the git page but I'm confused if it's complete/public/installable.

**Comment by jsychong** [comment]
Hi! It's not 100% ready at the moment, I will add more documentation/testing and it should be ready in the coming weeks.
