### ISSUE TITLE
Minimum % Prevalence in Samples

### ISSUE THREAD

**Issue by Aciole-David** [xia-lab/MicrobiomeAnalystR#2]
Hi
Since 05/29/2019 update of Microbiome Analyst Online (I'm sorry if this issue doesnt belong here) we can not decrease the minimum % prevalence in samples smaller than 10%. I remember we used to set all the filters to zero, because we did that outside Microbiome Analayst.
Is that parameter locked on >10% forever?
Thanks!

**Comment by jsychong** [comment]
Hi, you should be able to set all the sliders to 0 on the data filtering page. Cheers!

**Comment by Aciole-David** [comment]
Thanks for the answer. However, as you can see in the screenshot (using the Human Moving Picture example dataset), setting all filter o zero pops an error "validation error: value is out of range". This happens only when prevalence filter is below 10. The other filters keep at zero without errors.
But again, thanks for the attention. 

![Captura de Tela (13)](https://user-images.githubusercontent.com/29051553/60599726-56900100-9d85-11e9-83f7-b34fc82477ae.png)

**Comment by jsychong** [comment]
By setting the minimum count and percentage to remove sliders to 0, this disables the filtering step 
as no features would be removed. Whether the prevalence is 10% or 50% wouldn't matter in this circumstance. Using the Human Moving Picture data, the number of OTUs with >2 counts is 2920 before and after setting the sliders to 0.

**Comment by Aciole-David** [comment]
> By setting the minimum count and percentage to remove sliders to 0, this disables the filtering step
> as no features would be removed. Whether the prevalence is 10% or 50% wouldn't matter in this circumstance. Using the Human Moving Picture data, the number of OTUs with >2 counts is 2920 before and after setting the sliders to 0.

Ok, I understood now. Thanks.
Cheers
