### ISSUE TITLE
Manual download of MicrobiomeAnalystR.tar.gz link has a 404 error

### ISSUE THREAD

**Issue by Madegwa** [xia-lab/MicrobiomeAnalystR#5]
Hello, my name is Yvonne,I am enjoying using Microbiome Analyst online platform but i want to try and use it  in r software. I noticed that the link to manual installation has a 404 error. Is it possible to provide another link? Or the actual file?
Regards
Yvonne

**Comment by Aciole-David** [comment]
> Hello, my name is Yvonne,I am enjoying using Microbiome Analyst online platform but i want to try and use it in r software. I noticed that the link to manual installation has a 404 error. Is it possible to provide another link? Or the actual file?
> Regards
> Yvonne

Yvone, the devs are not answaering but maybe I can help or simply share my experience
Did you manage to install an run MicrobiomeAnalystR locally?
I was able to install and run the code in both linux (ubuntu/mint) and windows (7/10) using conda and much (MUCH) debug time installing sh*tloads of dependencies and adding missing files during build/install.
You can try downloading the zip from git or with devtools.
Anyway, I am currently creating scripts based on AnalystR just for "fun".
I've solved minor errors in a couple of functions, but for the majority of  remaining code I simply wont bother spending time reinventing the wheel.
The bugs mess things in the online version too.
Cheers

**Comment by rcsbiotech** [comment]
This program has a long history of incompatible issues and incompatible dependencies. I know a handful of competent people that have tried to install it in the past to no avail. I have a feeling that they (the devs) don't really want you to use MicrobiomeAnalyst outside of the web platform.

**Comment by Aciole-David** [comment]
> This program has a long history of incompatible issues and dependencies. I know a handful of competent people that have tried to install it in the past to no avail. I have a feeling that they (the devs) don't really want you to use MicrobiomeAnalyst outside of the web platform.

Indeed. Funny thing is: some bugs are on in the online version also

**Comment by jsychong** [comment]
Hi,

Thanks for your comments and feedbacks. I recently pushed a major update with the web version that should address the bugs, as well provide a link to the [tar.gz](https://www.dropbox.com/s/wk43rs9hswzypgt/MicrobiomeAnalystR_0.0.0.9000.tar.gz?dl=0) file for V 0.0.0.9 . Please note that this R package is at the moment under development and not yet ready for full functional use until announced. We have added a message stating its "in-progress" status to the repository. Note, we are responsive in a timely manner for any bugs reported for the online version of MicrobiomeAnalyst.ca (see the Contact us page). Fixes that we make for the online version directly reflect onto the R package. However, the current issues in the R package you are facing are mainly because of the required different code structuring and detailed documentation which we are working on. We will keep you posted once the R package is ready.

**Comment by Aciole-David** [comment]
> Hi,
> 
> Thanks for your comments and feedbacks. I recently pushed a major update with the web version that should address the bugs, as well provide a link to the [tar.gz](https://www.dropbox.com/s/wk43rs9hswzypgt/MicrobiomeAnalystR_0.0.0.9000.tar.gz?dl=0) file for V 0.0.0.9 . Please note that this R package is at the moment under development and not yet ready for full functional use until announced. We have added a message stating its "in-progress" status to the repository. Note, we are responsive in a timely manner for any bugs reported for the online version of MicrobiomeAnalyst.ca (see the Contact us page). Fixes that we make for the online version directly reflect onto the R package. However, the current issues in the R package you are facing are mainly because of the required different code structuring and detailed documentation which we are working on. We will keep you posted once the R package is ready.

Thanks 

> Hi,
> 
> Thanks for your comments and feedbacks. I recently pushed a major update with the web version that should address the bugs, as well provide a link to the [tar.gz](https://www.dropbox.com/s/wk43rs9hswzypgt/MicrobiomeAnalystR_0.0.0.9000.tar.gz?dl=0) file for V 0.0.0.9 . Please note that this R package is at the moment under development and not yet ready for full functional use until announced. We have added a message stating its "in-progress" status to the repository. Note, we are responsive in a timely manner for any bugs reported for the online version of MicrobiomeAnalyst.ca (see the Contact us page). Fixes that we make for the online version directly reflect onto the R package. However, the current issues in the R package you are facing are mainly because of the required different code structuring and detailed documentation which we are working on. We will keep you posted once the R package is ready.

Thank you all for the efforts
