### ISSUE TITLE
ERROR: Alpha diversity boxplot duplicating outliers

### ISSUE THREAD

**Issue by Aciole-David** [xia-lab/MicrobiomeAnalystR#9]
Hello,
is seems like the devs are not answering since Jul/2019, but:
I am posting this to help anyone strugling with the online version of Analyst
There's a litle bug in the alpha diversity boxplots which is duplicating the outliers:

https://github.com/xia-lab/MicrobiomeAnalystR/blob/master/R/mdp_utils.R
line 1143

   ```
geom_boxplot(alpha=0.7, aes(outlier.shape=1),  #this is duplicating the outliers
   geom_boxplot(alpha=0.7, outlier.shape=NA,      #this is my sugestion
```

See the attached plots
![alphabox](https://user-images.githubusercontent.com/29051553/75112075-23a1c280-561f-11ea-8ba0-e7399b4232cc.png)
![new-alphabox](https://user-images.githubusercontent.com/29051553/75112077-243a5900-561f-11ea-9e40-e39178150cc2.png)

**Comment by rocpengliu** [comment]
Hi, David

Thank you for reporting bug.

We have fixed this bug. Please be patient for pushing to the server (online
version).

For the R package, we are still in developing this R package and it is not
fully functional.

Thank you.

**Comment by Aciole-David** [comment]
Understood. Thanks
